# Generated by Django 3.2 on 2021-07-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseName', models.CharField(max_length=100)),
                ('course_Id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=100, unique=True)),
                ('floor', models.CharField(choices=[('1stFloor', '1stFloor'), ('2ndFloor', '2ndFloor'), ('3rdFloor', '3rdFloor')], max_length=100)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('course_id', models.ManyToManyField(related_name='courses', to='Exam.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('seats', models.IntegerField(default=0)),
                ('floor', models.CharField(max_length=100)),
                ('program', models.CharField(choices=[('Day', 'Day'), ('Evening', 'Evening')], max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exam.course')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.room')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exam.student')),
            ],
        ),
    ]
